'use strict';

const db = require('./db');

// calculate the amount of resources already used, the free amount of resources is retreived in the frontend
exports.getTotalResourcesUsed = () => {
    return new Promise ((resolve,reject) => {
        const sql = "SELECT COUNT(*) as instances, SUM(storage_tb) as totalStorage FROM orders"; 
        db.get(sql, (err, row) => {
            if(err) {
                reject(err);
            }
            resolve({
                instances: row.instances,
                totalStorage: row.totalStorage || 0
            });
        });
    });
};

//Add for a given userID
exports.addOrder = (userId, order) => {
    return new Promise((resolve, reject) => {
        const sql = `
            INSERT INTO orders (user_id, type_ram_id, storage_tb, transfer_gb)
            VALUES (?, ?, ?, ?)
        `;
        /**Orders informations */
        const params = [
            userId, 
            order.type_ram_id, 
            order.storage_tb, 
            order.transfer_gb
        ];

        db.run(sql, params, function (err) {
            if (err) {
                //Error sanitization, we remove the part 'ABORT' from the error generated by the trigger
                if (err.message.includes('SQLITE_CONSTRAINT') || err.message.includes('ABORT')) {
                    const errorMessage = err.message.split(': ').pop();
                    reject({ error: errorMessage }); 
                } else {
                   reject(err);
                }
            }
            resolve({ 
                id: this.lastID, 
                message: 'Order created successfully' 
            });
        });
    });
};

//Retreive the configuration raw to calculate costs and to set up limitations of free resources
exports.getConfiguration = () => {
    return new Promise((resolve, reject) => {
        const sqlConfig = "SELECT * FROM configuration WHERE id = 1";
        db.get(sqlConfig, (err, configRow) => {
            if (err) {
                reject(err);
            }
            if (configRow == undefined) {
                resolve({ error: 'Configuration setup not found.' });
            }
            const sqlRam = "SELECT * FROM comput_class";

            db.all(sqlRam, (err, ramRows) => {
                if (err) {
                    reject(err);
                }
                const response = {
                    ...configRow,
                    ramOptions: ramRows 
                };
                resolve(response);
            });
        });
    });
};

//Retreive orders by userId
exports.getOrdersById = (userId) => {
    return new Promise((resolve,reject) => {
        const sql = `
            SELECT O.id, O.storage_tb, O.transfer_gb, O.total_m_cost, C.ram_label 
            FROM orders O
            JOIN comput_class C ON O.type_ram_id = C.id
            WHERE O.user_id = ?
        `;
        db.all(sql, [userId], (err,rows) => {
            if(err){
                reject(err);
            }
            resolve(rows);
        })
    })
}

//delete orders given by userId and orderId (TOTP authN required)
exports.deleteOrder = (orderId, userId) => {
    return new Promise((resolve, reject) => {
        const sql = "DELETE FROM orders WHERE id = ? AND user_id = ?";
        
        db.run(sql, [orderId, userId], function (err) {
            if (err) {
                reject(err);
                return;
            }
            if (this.changes === 0) {
                reject({ error: 'Order not found or you are not authorized to delete it.' });
            } else {
                resolve({ message: 'Order deleted successfully' });
            }
        });
    });
};