'use strict';

/*** Importing modules ***/
const express = require('express');
const morgan = require('morgan');  // logging middleware
const { check, validationResult, oneOf } = require('express-validator'); // validation middleware
const cors = require('cors');

const cloudDao = require('./dao-cloud'); // module for accessing the films table in the DB
const userDao = require('./dao-users'); // module for accessing the user table in the DB

/*** init express and set-up the middlewares ***/
const app = express();
app.use(morgan('dev'));
app.use(express.json());


/** Set up and enable Cross-Origin Resource Sharing (CORS) **/
const corsOptions = {
  origin: 'http://localhost:5173', // only requests coming from this origin can access to server's resources
  credentials: true,
};
app.use(cors(corsOptions));


/*** Passport ***/

/** Authentication-related imports **/
const passport = require('passport');                              // authentication middleware
const LocalStrategy = require('passport-local');                   // authentication strategy (username and password)


const base32 = require('thirty-two');
const TotpStrategy = require('passport-totp').Strategy; // totp


// we set a local strategy, so we do authN with username(email) and password
passport.use(new LocalStrategy(async function verify(username, password, callback) {
  const user = await userDao.getUser(username, password)
  if(!user)
    return callback(null, false, 'Incorrect username or password');  
    
  return callback(null, user); // we have all the fields returned by getUser()
}));

// Serializing in the session the user object given from LocalStrategy(verify).
passport.serializeUser(function (user, callback) { // this user is id + username + name, generated by userDao.getUser()
    callback(null, user);
});

// Starting from the data in the session, we extract the current (logged-in) user.
passport.deserializeUser(function (user, callback) { // this user is id + email + name 
    return callback(null, user); // this will be available in req.user
});

/** Creating the session */
const session = require('express-session');

app.use(session({
  secret: "I hate JS, don't tell to anyone!",
  resave: false,
  saveUninitialized: false,
}));
app.use(passport.authenticate('session'));


passport.use(new TotpStrategy(
  function (user, done) {
    // In case .secret does not exist, decode() will return an empty buffer
    return done(null, base32.decode(user.secret), 30);  // 30 = period of key validity
  })
);

/** Defining authentication verification middleware **/
const isLoggedIn = (req, res, next) => {
  if(req.isAuthenticated()) {
    return next();
  }
  return res.status(401).json({error: 'Not authorized'});
}

function isTotp(req, res, next) {
  if(req.session.method === 'totp')
    return next();
  return res.status(401).json({ error: 'Missing TOTP authentication'});
}



/*** Utility Functions ***/

// GET /api/specifications
app.get('/api/specifications', async (req,res) => {
  try {
    const config = await cloudDao.getConfiguration();
    res.json(config);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Database error while retrieving configuration' });
  }
});

// GET /api/resources
app.get('/api/resources', async (req,res) => {
  try {
    const resources = await cloudDao.getTotalResourcesUsed();
    res.json(resources);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Database error while retrieving resources' });
  }
});

// POST /api/orders
app.post('/api/orders', isLoggedIn, 
  [
    check('type_ram_id').isInt({ min: 1, max: 3 }), 
    check('storage_tb').isInt({ min: 0 }), 
    check('transfer_gb').isInt({ min: 0 })
  ],
  async (req, res) => {
    // input validation
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(200).json({ success: false, errors: errors.array() });
    }

    const orderDetails = {
      type_ram_id: req.body.type_ram_id,
      storage_tb: req.body.storage_tb,
      transfer_gb: req.body.transfer_gb
    };

    try {
      const result = await cloudDao.addOrder(req.user.id, orderDetails);
      res.status(201).json(result);
    } catch (err) {
      if (err.error) {
        // we do not pass error 401 message, to keep console clean
        return res.status(200).json({ success: false, error: err.error });
      } else {
        console.error(err);
        res.status(503).json({ error: 'Database error during order creation' });
      }
    }
  }
);

// GET /api/orders
app.get('/api/orders', isLoggedIn, async (req,res) => {
  try {
    const orders = await cloudDao.getOrdersById(req.user.id);
    res.json(orders);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Database error while retrieving orders' });
  }
});

// DELETE /api/orders/:orderId
app.delete('/api/orders/:orderId', isLoggedIn, isTotp, [check('orderId').isInt({ min: 1 })],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(422).json({ errors: errors.array() });
    }

    try {
      // we pass both the user-id and the order-id, such that a user can only delete one of his orders.
      await cloudDao.deleteOrder(req.params.orderId, req.user.id);
      res.status(200).json({ message: 'Order deleted successfully' });
    } catch (err) {
      // Handle case in which order is not found or user is not authorized for that order
      if (err.error) {
        res.status(404).json({ error: err.error });
      } else {
        console.error(err);
        res.status(503).json({ error: 'Database error during deletion' });
      }
    }
  }
);


/*** Users APIs ***/

function clientUserInfo(req) {
  const user=req.user;
	return {id: user.id, username: user.username, name: user.name, canDoTotp: user.secret? true: false, isTotp: req.session.method === 'totp'};
}

// POST /api/sessions 
// This route is used for performing login.
app.post('/api/sessions', function(req, res, next) {
  passport.authenticate('local', (err, user, info) => { //info is defined in LocalStrategy
    if (err)
      return next(err);
      if (!user) {
        // display wrong login messages
        return res.status(401).json({ error: info});
      }
      // success, perform the login and extablish a login session, serializing the user object
      req.login(user, (err) => {
        if (err)
          return next(err);
        
        // req.user contains the authenticated user, we send all the user info back
        return res.json(clientUserInfo(req));
      });
  })(req, res, next);
});

app.post('/api/login-totp', isLoggedIn,
  // DEBUG: function(req,res,next){ console.log('DEBUG2: '+JSON.stringify(req.user)); next();},
  passport.authenticate('totp'),   // passport expect the totp value to be in: body.code
  function(req, res) {
    //console.log('DEBUG1: '+JSON.stringify(req.user));
    req.session.method = 'totp';
    res.json({otp: 'authorized'});
  }
);

// GET /api/sessions/current
// This route checks whether the user is logged in or not.
app.get('/api/sessions/current', (req, res) => {
  if(req.isAuthenticated()) {
    res.status(200).json(clientUserInfo(req));}
  else
    res.status(200).json({ isAuthenticated: false });
});

// DELETE /api/session/current
// This route is used for loggin out the current user.
app.delete('/api/sessions/current', (req, res) => {
  req.logout(() => {
    res.status(200).json({});
  });
});



// Activating the server
const PORT = 3001;
// Activate the server
app.listen(PORT, (err) => {
  if (err)
    console.log(err);
  else 
    console.log(`Server listening at http://localhost:${PORT}`);
}); 
